version: '3.11'
name: 'foodgram'
volumes:
  static_volume:
  media_volume:
  pg_data:
  redoc:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: amir800s/foodgram_backend
    restart: always
    env_file: .env
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - db
  frontend:
    image: amir800s/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static_volume:/static
  nginx:
    image: nginx:1.22.1
    env_file: .env
    volumes:
      - /home/user/Desktop/foodgram-project-react/nginx.conf:/etc/nginx/conf.d/
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
    depends_on:
      - backend
      - frontend
    ports:
      - '80:80'
