version: '3.9'
name: 'foodgram'
volumes:
  static_volume:
  media_volume:
  pg_data:
  redoc:

services:
  db:
    image: postgres:13.10-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    hostname: localhost
    restart: unless-stopped
  backend:
    depends_on:
      - db
    image: amir800s/foodgram_backend
    restart: always
    env_file: .env
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
  frontend:
    image: amir800s/foodgram_frontend
    env_file: .env
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    depends_on:
      - db
      - backend
    image: nginx:1.22.1
    ports:
      - '80:80'
    env_file: .env
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
