# Generated by Django 3.2.16 on 2023-09-26 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230918_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='shopping_cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipes.shoppingcartlist', verbose_name='Корзина покупок'),
        ),
    ]
