# Generated by Django 3.2.16 on 2023-09-26 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_shopping_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='shopping_cart',
        ),
    ]
