# ======= Константы для моделей =======
EMAIL_MAX_LENGHT = 254
USERNAME_AND_PASSWORD_MAX_LENGHT = 150
FIRST_USERNAME_MAX_LENGHT = 150
LAST_USERNAME_MAX_LENGHT = 150
INGREDIENT_MIN_AMOUNT = 1
INGREDIENT_MAX_AMOUNT = 10000
RECIPE_NAME_AND_TAGS = 200
TAG_COLOR = 7
